services:
  bibfiles:
    build: .
    image: bibfiles:latest
    container_name: bibfiles
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - bibfiles-network
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www/html

  mariadb:
    image: mariadb:11
    container_name: bibfiles_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: bibfiles
      MYSQL_USER: bibfiles
      MYSQL_PASSWORD: bibfiles
      MYSQL_ROOT_PASSWORD: bibfiles
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - bibfiles-network

  selenium:
    image: selenium/standalone-chrome
    container_name: bibfiles_selenium
    ports:
      - "7900:7900" # VNC (pra ver o browser rodando)
    networks:
      - bibfiles-network
    shm_size: 2gb

  senhaunica-faker:
    image: uspdev/senhaunica-faker
    container_name: bibfiles_senhaunica-faker
    ports:
      - "3141:3141"
    environment:
          - APP_URL=http://auth.local:3141
          - OAUTH_CONSUMER_KEY=faker
          - OAUTH_CONSUMER_SECRET=faker
    networks:
      bibfiles-network:
        aliases:
          - auth.local

networks:
  bibfiles-network:

volumes:
  mariadb_data:

